/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CheatsheetTechImport } from './routes/cheatsheet/$tech'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CheatsheetTechRoute = CheatsheetTechImport.update({
  path: '/cheatsheet/$tech',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cheatsheet/$tech': {
      id: '/cheatsheet/$tech'
      path: '/cheatsheet/$tech'
      fullPath: '/cheatsheet/$tech'
      preLoaderRoute: typeof CheatsheetTechImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/cheatsheet/$tech': typeof CheatsheetTechRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cheatsheet/$tech': typeof CheatsheetTechRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/cheatsheet/$tech': typeof CheatsheetTechRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cheatsheet/$tech'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cheatsheet/$tech'
  id: '__root__' | '/' | '/cheatsheet/$tech'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CheatsheetTechRoute: typeof CheatsheetTechRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CheatsheetTechRoute: CheatsheetTechRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cheatsheet/$tech"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/cheatsheet/$tech": {
      "filePath": "cheatsheet/$tech.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
